kyrolabs/awesome-langchain

README.md

Adding a code-along tutorial on LangChain and LLM monitoring + a recent YouTube video featuring LangChain's Harrison Chase

Update README.md to include recent YT video and blog/tutorial on LLM agent monitoring

---

README.md

Just adding my article here :) 
Deploy a Voice-Based Chatbot with BentoML, LangChain, and Gradio
https://towardsdatascience.com/deploy-a-voice-based-chatbot-with-bentoml-langchain-and-gradio-7f25af3e45df

Add Medium blog post to README.md

---

README.md

fix:minor typo

---

README.md

Add two webinars about LangChain hosted on crowdcast and a LangChain tutorial at PromptChap.

add two crowdcast webinars and promptchap tutorial

---

README.md

[CoFounder](https://co-founder.ai?utm_source=langchain&utm_medium=gallary&utm_campaign=alpha) is a platform to revolutionize the start-up ecosystem by providing founders with unparalleled tools, resources, and support. We are changing how founders build their companies from 0-1—productizing the accelerator/incubator programs using AI.
We are starting with the following features:
* AI Investor Matching and Introduction and Tracking
* AI Pitch Deck creation
* Real-time Pitch Deck practice/feedback
* Automatic Competitive Analysis / Watchlist
It uses Langchain to create a context for each company on the platform. Our algorithms then use it to create recommendations for the founders and investors.

Update CoFounder link and description

---

README.md

Added Graphsignal to Tools and Services

Add Graphsignal to Tools/Services

---

README.md

Hi, could you please add LangChain4j to the list?
Thank you!

Added LangChain4j

---

README.md

Twitter Agent scrapes data from Twitter and leverages the power of Large Language Models (LLMs) to interactively chat with the extracted tweets 💬, summarize them 📝 and provide conversation ideas 💡.
Twitter Agent helps you quickly gather insights on real-time events such as news, build a technical knowledge on your favourite programming language or research any topic that interests you.

Add Twitter Agent project

---

README.md

Put DemoGPT to the end of the list

DemoGPT updated to bottom

---

README.md

This [post](https://wyh.life/article/2023/07/02/llm-app-development) summarize the development experience and some thoughts about building an LLM application ([BlogGPT](https://github.com/yaohui-wyh/blog_gpt)) using the [LangChain](https://github.com/hwchase17/langchain) framework.

[Article] Add BlogGPT development notes 

---

README.md

- added to agents list > autonomous-hr-chatbot
- added to articles list>  'Creating a (mostly) Autonomous HR Assistant with ChatGPT and LangChain’s Agents and Tools'. The article was 'boosted' on medium and has 500+ claps.

added autonomous-hr-chatbot agent

---

README.md

BlockAGI is an open-source research agent built with Python3, utilizing the capabilities of [LangChain](https://github.com/hwchase17/langchain) and [OpenAI](https://openai.com/). BlockAGI conducts iterative, domain-specific research, primarily focused on cryptocurrency but customizable to other domains. It outputs detailed narrative reports to showcase its findings.
https://github.com/blockpipe/BlockAGI

Add BlockAGI to the list of agents

---

README.md

LangChainJSDotNet provides a seamless interface for .NET developers to run LangChain based code with minimal adjustments.

Added LangChainJSDotNet

---

README.md

[examor](https://github.com/codeacme17/examor): A website application that allows you to take exams based on your knowledge notes. Let you really remember the notes you wrote

Add examor

---

README.md

waggledance.ai is intended to be a general goal solver. Goals can include things like research, workflow automation, synthesis of live data, etc.-- things that ChatGPT can do with plugins, considerable chatting and effort.
The general concept is that it takes your data, allows you to configure tools (aka skills), and then runs a plan-validate-solve system of agents.There are some example goals in the UI. Agents are throw-away, i.e., there isn't a "code agent" or "Einstein agent", however there are three distinct agent types. Plan, execute, and critique. 
Most of the effort so far has been spent trying to optimize the time-to-first-byte and think about different ways agents may be interacted with. I also have been optimizing parallel execution of tasks to reduce the total amount of time to …

Add waggledance.ai to #Agents

---

README.md

This is an implementation of a chatbot using LLM chat model API and Langchain. We can see is as a hands-on project while we are updating and applying new techniques like LangSmith or LECL to this bot.

Add Personality Chatbot

---

README.md

Adding GPT Researcher the leading open source autonomous online research agent, also powered by Langchain.

Added GPT Researcher

---

README.md

uAgents is a library developed by Fetch.ai that allows for creating autonomous AI agents in Python. With simple and expressive decorators, you can have an agent that performs various tasks on a schedule or takes action on various events.
**🚀 Features**
- 🤖 Easy creation and management: Create any type of agent you can think of and put into code.
- 🔗 Connected: On startup, each agent automatically joins the fast growing network of uAgents by registering on the Almanac, a smart contract deployed on the Fetch.ai blockchain.
- 🔒 Secure: uAgent messages and wallets are cryptographically secured, so their identities and assets are protected.

Add uAgents: AI Agent Framework

---

README.md

Add InkChatGPT

---

README.md

Added MindsDB to platforms.
MindsDB integrates with numerous [data sources](https://docs.mindsdb.com/integrations/data-overview), including databases, vector stores, and applications, and popular [AI/ML frameworks](https://docs.mindsdb.com/integrations/ai-overview), including AutoML and LLM.With MindsDB, you can connect any data source to any AI/ML model to implement and automate AI-powered applications. Deploy, serve, and fine-tune models in real-time, utilizing data from databases, vector stores, or applications. Do all that using universal tools developers already know.

Added MindsDB

---

README.md

Hello maintainers,
I would like to propose adding the [llama-github](https://github.com/JetXu-LLM/llama-github) Python library to the awesome-langchain list. Llama-github is a powerful tool that retrieves highly relevant code snippets, issues, and repository information from GitHub based on user queries, transforming them into valuable knowledge context for LLM Chatbots, AI Agents, and Auto-dev Agents.
Key features of llama-github include:
1. **Efficient Coding Knowledge Retrieval**: Advanced retrieval techniques ensure the most pertinent information is found quickly and efficiently.
2. **Repository Pool Caching**: An innovative caching mechanism significantly accelerates GitHub search retrieval efficiency and minimizes the consumption of GitHub API tokens.
3. **Advanced Question …

Add Llama-github python library to Tools/Service list bottom

---

README.md

I’m excited to share my latest repo with you—a local conversational RAG solution for your files! This setup is perfect for running RAG on-premises. It’s built with Docker, LangChain, Ollama, FastAPI, and Hugging Face, and all models are downloaded automatically. Also, you can index all files locally and use ChatGPT or Claude.
Thank you!

Add Minima

---

README.md

Dear maintainers,
I would like to propose adding [Flock](https://github.com/Onelevenvy/flock) to the awesome-langchain list. Flock is a workflow-based low-code platform for rapidly building chatbots, RAG applications, and coordinating multi-agent teams. Built on LangChain and LangGraph, it provides a flexible, low-code orchestrating solution for collaborative agents.
- Multiple node types (LLM, Retrieval, Tool Call, Interrupt，Intent Recognition, If-Else etc.)
- Visual workflow orchestration
- Subgraph node support for modular design
- Support for various model providers (OpenAI, ZhipuAI, Ollama, etc.)
- Built-in tools and custom tool support
- Multimodal chat capabilities
- Human-in-the-loop support
- Intent recognition routing
- Persistent conversation history
Additionally, Flock …

Add flock to Service list 

---

README.md

Proposal to add LangWatch to the services section of the list!

Add LangWatch to the services section

---

README.md

These ports are currently being maintained. Let me know if anything else is required. Thanks!

Add Haskell, Rust and Elixir to port list
